site_name: Sistemas operativos monopuesto
site_url: https://joperpu.github.io/som2526
theme:
  name: material
  language: es
  favicon: assets/images/logo.ico
  features:
    - content.code.copy
  palette: 
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: "assets/images/logo.png"
nav:
  - Página principal: index.md
  - Unidad 1 - Introducción a los sistemas operativos:
    - Teoría UD1: ud1.md
    - Práctica 1.1: pr1.1.md
  - Unidad 2 - Instalación y máquinas virtuales con Windows y Linux:
    - Teoría UD2 - Sistemas operativos y VirtualBox: ud2.1.md
    - Teoría UD2 - Instalación de Windows 11: ud2.2.md
    - Teoría UD2 - Instalación de GNU/Linux: ud2.3.md
    - Teoría UD2 - Instalación de Windows-Linux dual: ud2.4.md
    - Teoría UD2 - Creación de un pendrive booteable: ud2.5.md
    - Teoría UD3 - Creación y restauración de imágenes: ud2.6.md
    - Práctica 2.1: pr2.1.md
    - Práctica 2.2: pr2.2.md
    - Práctica 2.3: pr2.3.md
    - Práctica 2.4: pr2.4.md
  #- Unidad 3 - Configuración y administración de sistemas operativos basados en GNU/Linux:
    #- Teoría UD3 - Introducción a Lubuntu y comandos iniciales: ud3.1.md
    #- Teoría UD3 - Gestión de archivos en Lubuntu: ud3.2.md
    #- Práctica 3.1: pr3.1.md
    #- Práctica 3.2: pr3.2.md

copyright: "2025 José María Pérez Puentes - Licencia CC BY-NC-SA 4.0"

extra:
  generator: true

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - admonition
  - pymdownx.details